parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Vdm\Bundle\LibraryHttpTransportBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Vdm\Bundle\LibraryHttpTransportBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Vdm\Bundle\LibraryHttpTransportBundle\Transport\HttpTransportFactory:
        autowire: true
        tags: [messenger.transport_factory]
